#server:
#  port: 9092
#  
# 
#spring:
#  application:
#    name: ACCOUNT-SERVICE
#  config:
#    import: optional:configserver:http://localhost:9296 
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/microservicedb
#    username: postgres
#    password: root
#      
## Hibernate ddl auto (create, create-drop, validate, update)
#
##spring.jpa.hibernate.ddl-auto=update
##spring.jpa.show-sql=true
#
##spring.datasource.driver-class-name=org.postgresql.Driver
##spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
##spring.datasource.url=jdbc:postgresql://localhost:5432/hr
##spring.datasource.username=postgres
##spring.datasource.password=root
#
#
##eureka:
##  client:
##    register-with-eureka: true
##    fetch-registry: true
##    service-url:
##      defaultZone: http://localhost:8761/eureka/
##  instance:
##      hostname: localhost
#
